/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    collections: Collection;
    pages: Page;
    products: Product;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    collections: CollectionsSelect<false> | CollectionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en' | 'ru') | ('fr' | 'en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    'design-tokens': DesignToken;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'design-tokens': DesignTokensSelect<false> | DesignTokensSelect<true>;
  };
  locale: 'fr' | 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Curated product groups — Été 2026, Sacs, Nouveautés. Never one Page per SKU.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections".
 */
export interface Collection {
  id: number;
  title: string;
  /**
   * URL segment for /collections/[slug]
   */
  slug: string;
  /**
   * Optional editorial hero for the collection page.
   */
  hero?: (number | null) | Media;
  /**
   * Drag to reorder — storefront respects this order.
   */
  products?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Auto-generated from title if left blank.
   */
  slug: string;
  category: 'dresses' | 'bags' | 'scarfs';
  /**
   * Price in EUR (e.g. 290.00)
   */
  price: number;
  /**
   * Uncheck to show as out of stock — buyers can express interest via WhatsApp.
   */
  inStock?: boolean | null;
  /**
   * Editorial truth only — small-series production. No countdown or stock pressure.
   */
  limitedSeries?: boolean | null;
  mainImage: number | Media;
  /**
   * Additional product photos (shown after the main image).
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Product description shown on the detail page.
   */
  description?: string | null;
  availableLengths?: ('longer' | 'shorter')[] | null;
  availableSizes?: ('XS' | 'S' | 'M' | 'L' | 'XL')[] | null;
  pairings?: (number | Product)[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Use 'home' for the storefront homepage.
   */
  slug: string;
  blocks?:
    | (
        | {
            heroImage: number | Media;
            /**
             * Optional muted loop (max 8 s). Poster uses the hero image. Respects reduced-motion.
             */
            heroVideo?: (number | null) | Media;
            /**
             * Shows a quiet « limited series » line on the home hero (The Row cadence).
             */
            showCapsuleBadge?: boolean | null;
            season: string;
            tagline: string;
            ctaLabel: string;
            ctaLink: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            sourceType?: ('manual' | 'collection') | null;
            title: string;
            viewCollectionLabel?: string | null;
            collection?: (number | null) | Collection;
            products?: (number | Product)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featuredProducts';
          }
        | {
            label: string;
            headline: string;
            subline: string;
            body: string;
            ctaLabel: string;
            ctaLink: string;
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'editorialStrip';
          }
        | {
            title: string;
            sourceType?: ('all' | 'collection') | null;
            collection?: (number | null) | Collection;
            id?: string | null;
            blockName?: string | null;
            blockType: 'productGrid';
          }
      )[]
    | null;
  body?: string | null;
  cover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Orders placed by buyers. Read-only — fulfilment happens on WhatsApp.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  product?: (number | null) | Product;
  /**
   * Product title snapshot at order time (set server-side).
   */
  productTitle?: string | null;
  /**
   * Category snapshot at order time (set server-side).
   */
  category?: ('dresses' | 'bags' | 'scarfs') | null;
  length?: ('longer' | 'shorter') | null;
  size?: ('XS' | 'S' | 'M' | 'L' | 'XL') | null;
  /**
   * Price snapshot at order time (set server-side).
   */
  price?: number | null;
  buyerName: string;
  /**
   * Buyer phone number.
   */
  buyerContact: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'collections';
        value: number | Collection;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_select".
 */
export interface CollectionsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  hero?: T;
  products?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heroImage?: T;
              heroVideo?: T;
              showCapsuleBadge?: T;
              season?: T;
              tagline?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        featuredProducts?:
          | T
          | {
              sourceType?: T;
              title?: T;
              viewCollectionLabel?: T;
              collection?: T;
              products?: T;
              id?: T;
              blockName?: T;
            };
        editorialStrip?:
          | T
          | {
              label?: T;
              headline?: T;
              subline?: T;
              body?: T;
              ctaLabel?: T;
              ctaLink?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              sourceType?: T;
              collection?: T;
              id?: T;
              blockName?: T;
            };
      };
  body?: T;
  cover?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  price?: T;
  inStock?: T;
  limitedSeries?: T;
  mainImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  description?: T;
  availableLengths?: T;
  availableSizes?: T;
  pairings?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  product?: T;
  productTitle?: T;
  category?: T;
  length?: T;
  size?: T;
  price?: T;
  buyerName?: T;
  buyerContact?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global brand settings — social links, contact details, brand identity.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Displayed in page titles and contact headers.
   */
  brandName: string;
  /**
   * Large header wordmark text — e.g. LÉNUE
   */
  brandWordmarkPrimary?: string | null;
  /**
   * Small sub-line under the wordmark — e.g. PARIS. Leave empty for single-line brands.
   */
  brandWordmarkSecondary?: string | null;
  /**
   * Full URL — e.g. https://www.instagram.com/yourhandle
   */
  instagramUrl?: string | null;
  /**
   * International format without + or spaces — e.g. 33612345678
   */
  whatsappPhone?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand colours. Changes propagate immediately — no deploy needed.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-tokens".
 */
export interface DesignToken {
  id: number;
  /**
   * Headings, product titles, nav. → text-primary
   */
  colorPrimary?: string | null;
  /**
   * Body text, descriptions. → text-secondary
   */
  colorSecondary?: string | null;
  /**
   * Labels, captions. → text-muted
   */
  colorMuted?: string | null;
  /**
   * Decorative text, inactive states. → text-subtle
   */
  colorSubtle?: string | null;
  /**
   * Global body background. → bg-page-bg
   */
  colorPageBg?: string | null;
  /**
   * Cards, panels, header background. → bg-surface
   */
  colorSurface?: string | null;
  /**
   * Warm tinted bg for editorial strip sections. → bg-editorial
   */
  colorEditorial?: string | null;
  /**
   * Warm tinted bg for quote and feature sections. → bg-section
   */
  colorSection?: string | null;
  /**
   * Placeholder background for loading states. → bg-skeleton
   */
  colorSkeleton?: string | null;
  /**
   * Button backgrounds, strong borders, focus rings. → bg-accent, border-accent, ring-accent
   */
  colorAccent?: string | null;
  /**
   * Button hover colour. → hover:bg-accent-hover
   */
  colorAccentHover?: string | null;
  /**
   * Text colour on accent buttons. → text-accent-text
   */
  colorAccentText?: string | null;
  /**
   * Header borders, card edges, dividers. → border-subtle, divide-subtle
   */
  colorBorder?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  brandName?: T;
  brandWordmarkPrimary?: T;
  brandWordmarkSecondary?: T;
  instagramUrl?: T;
  whatsappPhone?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-tokens_select".
 */
export interface DesignTokensSelect<T extends boolean = true> {
  colorPrimary?: T;
  colorSecondary?: T;
  colorMuted?: T;
  colorSubtle?: T;
  colorPageBg?: T;
  colorSurface?: T;
  colorEditorial?: T;
  colorSection?: T;
  colorSkeleton?: T;
  colorAccent?: T;
  colorAccentHover?: T;
  colorAccentText?: T;
  colorBorder?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}